### ISSUE TITLE
Have problem with juce and maximilian

### ISSUE THREAD

**Issue by HongLouWang** [cpenny42/JUCE_Fluidsynth#1]
I want to use an ADSR from maximilian and the juse DSP, what should I do

**Comment by cpenny42** [comment]
Given that both are just C++ libraries, this shouldn't be difficult. 

I'd recommend you pick one as the main "host" that actually sends samples to the DAC. Then you can use the other in your audio rendering function.

I don't have any experience with Maximilian, but it looks pretty straightforward. I'd recommend making an Audio app in JUCE, then using whatever features you want from the maximilian library in JUCE's `renderNextBlock` function.

Here's a forum post that seems to do something very similar:

https://forum.juce.com/t/adsr-sustain-and-release-stage-not-working-properly/32978

JUCE has plenty of tools for ADSRs, and probably pretty much everything else that's in maximilian, but you definitely don't need to stick with them — you can use whatever you want for an ADSR. At the end of the day it's just multiplying a varying gain level with the incoming samples.

This specific Github repo is for the Fluidsynth library, which makes it easy to use soundfonts with JUCE. The soundfont specification also has its own attack/sustain/release logic, and as far as I know there isn't a direct way to override the ADSR within fluidsynth — it would mean diving pretty deep into ancient C code. You could create a soundfont with instant attack and a long release, and then apply another ADSR on top of it, but that would be monophonic and probably not what you want at all.

If you need to use soundfonts (and not just regular non-soundfont synths), I'd recommend instead the SFZero project, which is another library that brings soundfonts to JUCE. It's a newer codebase and is a lot easier to extend or change in some way. You could definitely combine some maximilian elements with that — it would be how I approached the issue if I were you.

https://github.com/altalogix/SFZero


If you're actually just looking for info on using JUCE with Maximilian and don't care at all about soundfonts, I just googled "juce maximilian" and this repo popped up. Looks pretty interesting!

https://github.com/fedden/juceSynths

If you are new to all this, check out the JUCE forums (but be a little bit more specific when you post 😉). They are always pretty active, I usually get quick responses from people.

https://forum.juce.com/
